### ISSUE TITLE
Can't build in vs2015 after version 2.0.0

### ISSUE THREAD

**Issue by yzhgu** [utelle/SQLite3MultipleCiphers#195]
I think the cipher scheme AEGIS introduced in version 2.0.0 broke the build in vs2015. For vs2019/2022, it works fine.
~~~
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289644): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289644): error C2719: 'b': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289650): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289650): error C2719: 'b': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289670): error C2719: 'b': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289677): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289677): error C2719: 'b': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289683): error C2719: 'd1': formal parameter with requested alignment of 16 won't be aligned
1>l:\workingdir\tools\3rd\wxsqlite3\src\sqlite3mc_amalgamation.c(289683): error C2719: 'd2': formal parameter with requested alignment of 16 won't be aligned
~~~

**Comment by utelle** [comment]
> I think the cipher scheme AEGIS introduced in version 2.0.0 broke the build in vs2015. For vs2019/2022, it works fine.

VS2015 is a rather old compiler. If you really need to use VS2015, a workaround would be to disable the _AEGIS_ cipher by defining the precompiler symbol on the command line `/DHAVE_CIPHER_AEGIS=0` or in source code

```
#define HAVE_CIPHER_AEGIS 0
```

The problem is that VS2015 is very strict regarding alignment. VS2017 and above implicitly take care of passing parameters with alignment correctly.

The _AEGIS_ cipher scheme is actually implemented via the third-party library [libaegis](https://github.com/aegis-aead/libaegis), although the code (with some adjustments to allow amalgamation) is included in this project.

Supporting VS2015 would require to change the affected functions to pass the arguments by reference (pointers) instead of by value. This would be a major change, and would make updating to newer _libaegis_ versions much more difficult. If you can convince the _libaegis_ developers to apply this change, I will apply it as well.
